save_dir: save/
model_name: Hi-VT5
# model_weights: t5-base
# model_weights: weights/hivt5_custom_mp-docvqa__best.ckpt
model_weights: rubentito/hivt5-base-mpdocvqa
freeze_encoder: False
page_tokens: 10
device: cuda

retrieval_module:
  loss: CrossEntropy
  loss_weight: 0.25

visual_module:
  model: dit  # 'vit' / 'dit'
  finetune: false
  model_weights: microsoft/dit-base-finetuned-rvlcdip  # 'google/vit-base-patch16-224-in21k' / 'microsoft/dit-base-finetuned-rvlcdip'
  # model_weights: rubentito/hivt5-base-mpdocvqa  # 'google/vit-base-patch16-224-in21k' / 'microsoft/dit-base-finetuned-rvlcdip'

training_parameters:
  max_pages: 2
  lr: 2e-4  # 2e-4
  batch_size: 16
  train_epochs: 10
  warmup_iterations: 1000
  seed: 42
