save_dir: save/
model_name: LayoutLMv3
# model_weights: microsoft/layoutlmv3-base  # 1e-4
# model_weights: xhyi/layoutlmv3-large_docvqa_t13c11000
# model_weights: weights/layoutlmv3_oracle_mp-docvqa.ckpt
model_weights: rubentito/layoutlmv3-base-mpdocvqa
device: cuda
data_parallel: False

training_parameters:
  lr: 1e-4
  batch_size: 2
  train_epochs: 10
  warmup_iterations: 1000
