save_dir: save/
model_name: Longformer
# model_weights: valhalla/longformer-base-4096-finetuned-squadv1
# model_weights: mrm8488/longformer-base-4096-finetuned-squadv2
# model_weights: allenai/longformer-base-4096-finetuned-triviaqa
model_weights: rubentito/longformer-base-mpdocvqa
device: cuda
data_parallel: True

training_parameters:
  lr: 1e-4  # (Longformer Colab) # 3e-5  # (Original Longformer paper) # 2e-4  # (LayoutHT5)
  batch_size: 8
  train_epochs: 10
  warmup_iterations: 1000

