save_dir: save/
model_name: Longformer
model_weights: rubentito/longformer-base-mpdocvqa
device: cuda

training_parameters:
  lr: 1e-4  # (Longformer Colab) # 3e-5  # (Original Longformer paper) # 2e-4
  batch_size: 8
  train_epochs: 10
  warmup_iterations: 1000
